name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    env:
      ENVIRONMENT: Test
    steps:
      - name: Test
        run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    env:
      ENVIRONMENT: Load-Test
    steps:
      - name: Load Test
        run: |
          echo "🧪 Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: ${{ github.event.inputs.environment == 'Production' }}
    env:
      ENVIRONMENT: Production
    steps:
      - name: Deploy to Production
        run: |
          echo "🚀 Step 1..."
          sleep 10
          echo "🚀 Step 2..."
          sleep 10
          echo "🚀 Step 3..."
          sleep 10
          echo "🚀 Step 4..."
          sleep 10
          echo "🚀 Step 5..."
